/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWorkorderRouteImport } from './routes/api/workorder'
import { Route as ApiVerifyIdentityRouteImport } from './routes/api/verify-identity'
import { Route as ApiTenantRouteImport } from './routes/api/tenant'
import { Route as AppWorkOrdersRouteImport } from './routes/_app.work-orders'
import { Route as AppTenantsRouteImport } from './routes/_app.tenants'
import { Route as ApiWorkorderWorkOrderIdRouteImport } from './routes/api/workorder.$workOrderId'
import { Route as ApiTenantTenantIdRouteImport } from './routes/api/tenant.$tenantId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkorderRoute = ApiWorkorderRouteImport.update({
  id: '/api/workorder',
  path: '/api/workorder',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyIdentityRoute = ApiVerifyIdentityRouteImport.update({
  id: '/api/verify-identity',
  path: '/api/verify-identity',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTenantRoute = ApiTenantRouteImport.update({
  id: '/api/tenant',
  path: '/api/tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkOrdersRoute = AppWorkOrdersRouteImport.update({
  id: '/work-orders',
  path: '/work-orders',
  getParentRoute: () => AppRoute,
} as any)
const AppTenantsRoute = AppTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AppRoute,
} as any)
const ApiWorkorderWorkOrderIdRoute = ApiWorkorderWorkOrderIdRouteImport.update({
  id: '/$workOrderId',
  path: '/$workOrderId',
  getParentRoute: () => ApiWorkorderRoute,
} as any)
const ApiTenantTenantIdRoute = ApiTenantTenantIdRouteImport.update({
  id: '/$tenantId',
  path: '/$tenantId',
  getParentRoute: () => ApiTenantRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tenants': typeof AppTenantsRoute
  '/work-orders': typeof AppWorkOrdersRoute
  '/api/tenant': typeof ApiTenantRouteWithChildren
  '/api/verify-identity': typeof ApiVerifyIdentityRoute
  '/api/workorder': typeof ApiWorkorderRouteWithChildren
  '/api/tenant/$tenantId': typeof ApiTenantTenantIdRoute
  '/api/workorder/$workOrderId': typeof ApiWorkorderWorkOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tenants': typeof AppTenantsRoute
  '/work-orders': typeof AppWorkOrdersRoute
  '/api/tenant': typeof ApiTenantRouteWithChildren
  '/api/verify-identity': typeof ApiVerifyIdentityRoute
  '/api/workorder': typeof ApiWorkorderRouteWithChildren
  '/api/tenant/$tenantId': typeof ApiTenantTenantIdRoute
  '/api/workorder/$workOrderId': typeof ApiWorkorderWorkOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/tenants': typeof AppTenantsRoute
  '/_app/work-orders': typeof AppWorkOrdersRoute
  '/api/tenant': typeof ApiTenantRouteWithChildren
  '/api/verify-identity': typeof ApiVerifyIdentityRoute
  '/api/workorder': typeof ApiWorkorderRouteWithChildren
  '/api/tenant/$tenantId': typeof ApiTenantTenantIdRoute
  '/api/workorder/$workOrderId': typeof ApiWorkorderWorkOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tenants'
    | '/work-orders'
    | '/api/tenant'
    | '/api/verify-identity'
    | '/api/workorder'
    | '/api/tenant/$tenantId'
    | '/api/workorder/$workOrderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tenants'
    | '/work-orders'
    | '/api/tenant'
    | '/api/verify-identity'
    | '/api/workorder'
    | '/api/tenant/$tenantId'
    | '/api/workorder/$workOrderId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/tenants'
    | '/_app/work-orders'
    | '/api/tenant'
    | '/api/verify-identity'
    | '/api/workorder'
    | '/api/tenant/$tenantId'
    | '/api/workorder/$workOrderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ApiTenantRoute: typeof ApiTenantRouteWithChildren
  ApiVerifyIdentityRoute: typeof ApiVerifyIdentityRoute
  ApiWorkorderRoute: typeof ApiWorkorderRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workorder': {
      id: '/api/workorder'
      path: '/api/workorder'
      fullPath: '/api/workorder'
      preLoaderRoute: typeof ApiWorkorderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify-identity': {
      id: '/api/verify-identity'
      path: '/api/verify-identity'
      fullPath: '/api/verify-identity'
      preLoaderRoute: typeof ApiVerifyIdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tenant': {
      id: '/api/tenant'
      path: '/api/tenant'
      fullPath: '/api/tenant'
      preLoaderRoute: typeof ApiTenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/work-orders': {
      id: '/_app/work-orders'
      path: '/work-orders'
      fullPath: '/work-orders'
      preLoaderRoute: typeof AppWorkOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tenants': {
      id: '/_app/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof AppTenantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/workorder/$workOrderId': {
      id: '/api/workorder/$workOrderId'
      path: '/$workOrderId'
      fullPath: '/api/workorder/$workOrderId'
      preLoaderRoute: typeof ApiWorkorderWorkOrderIdRouteImport
      parentRoute: typeof ApiWorkorderRoute
    }
    '/api/tenant/$tenantId': {
      id: '/api/tenant/$tenantId'
      path: '/$tenantId'
      fullPath: '/api/tenant/$tenantId'
      preLoaderRoute: typeof ApiTenantTenantIdRouteImport
      parentRoute: typeof ApiTenantRoute
    }
  }
}

interface AppRouteChildren {
  AppTenantsRoute: typeof AppTenantsRoute
  AppWorkOrdersRoute: typeof AppWorkOrdersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppTenantsRoute: AppTenantsRoute,
  AppWorkOrdersRoute: AppWorkOrdersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiTenantRouteChildren {
  ApiTenantTenantIdRoute: typeof ApiTenantTenantIdRoute
}

const ApiTenantRouteChildren: ApiTenantRouteChildren = {
  ApiTenantTenantIdRoute: ApiTenantTenantIdRoute,
}

const ApiTenantRouteWithChildren = ApiTenantRoute._addFileChildren(
  ApiTenantRouteChildren,
)

interface ApiWorkorderRouteChildren {
  ApiWorkorderWorkOrderIdRoute: typeof ApiWorkorderWorkOrderIdRoute
}

const ApiWorkorderRouteChildren: ApiWorkorderRouteChildren = {
  ApiWorkorderWorkOrderIdRoute: ApiWorkorderWorkOrderIdRoute,
}

const ApiWorkorderRouteWithChildren = ApiWorkorderRoute._addFileChildren(
  ApiWorkorderRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ApiTenantRoute: ApiTenantRouteWithChildren,
  ApiVerifyIdentityRoute: ApiVerifyIdentityRoute,
  ApiWorkorderRoute: ApiWorkorderRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
